### ISSUE TITLE
Questions about dfde.

### ISSUE THREAD

**Issue by mengchaoheng** [ZJU-FAST-Lab/Swarm-Formation#18]
Hi, thanks for the great work! I learned the formula (5) of the gradient of formation similarity distance metric `f` with respect to position `p_i` from the paper[1],  before that, we need (8), but there is no specific expression for (8). 

I saw the calculation of `dfde` from the [code](https://github.com/ZJU-FAST-Lab/Swarm-Formation/blob/cced7271064a78510701872f4a933d075de733eb/src/planner/swarm_graph/src/swarm_graph.cpp#L112-L127), it should be related to equation (6) and (9). Before calculating (6), we need (8), but the code does not correspond to equation (8). Is there a more detailed derivation of (8)? Does it just use the chain rule of Matrix Calculus to solve for partial derivatives (8)? From a reader's perspective, I think intuitive derivation or code is more conducive to the dissemination of knowledge. Hope to get your reply. Thanks again!

[1] L. Quan, L. Yin, C. Xu, and F. Gao, “Distributed Swarm Trajectory Optimization for Formation Flight in Dense Environments,” in 2022 International Conference on Robotics and Automation (ICRA), May 2022, pp. 4979–4985. doi: [10.1109/ICRA46639.2022.9812050](https://doi.org/10.1109/ICRA46639.2022.9812050).

**Comment by SamuraiChamploo** [comment]
I apologize for the late response. 
Regarding equation (8), the article did not provide a more detailed derivation of the formula. Due to the complexity of the original problem formulation, we could only present the analytical form of equation (8). In actual solving, we utilized the symbolic computation tools in Mathematica to obtain a lengthy expression, which was then translated into the code structure shown.

Understanding this part primarily relies on grasping the underlying principles, as it is challenging to comprehend through the step-by-step process of actual calculations.
